---
# tasks file for roles/ubuntu/docker
# Installation of Docker and Dependencies <START>
- name: Install Prerequisites
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Docker File
  apt: 
    name: docker.io
    state: latest
    update_cache: yes
  register: docker

- name: Install docker.py
  pip:
    name: docker.py
    state: latest

- name: Installation of docker-py package
  pip: name=docker-py
# Installation of Docker and Dependencies <END>


# Creating docker directory and copying Dockerfiles <START>
- name: Creating Build Directory
  file:
    path: "/home/atoraja/Toraja_CONTAINERIZATION/docker"
    state: directory

- name: Copying Dockerfile
  copy:
    src: "/home/atoraja/Toraja_CONTAINERIZATION/Dockerfile"
    dest: "/home/atoraja/Toraja_CONTAINERIZATION/docker/Dockerfile"
# Creating Docker dorectory and copying Dockerfiles <END>

# Creating Docker Container <START> 
- name: Building Container Image
  docker_image:
    name: hoa5-1
    tag: v1
    path: "/home/atoraja/Toraja_CONTAINERIZATION/docker"
    state: build
# Creating Docker Container <END>

# Running the created Docker Container <START>
- name: Running the Container
  docker_container:
    image: hoa5-1:v1
    name: hoa5-1
    state: started
    ports:
      - "8080:80"   
# Running the created Docker Container <END>
